<?php
// --------------------------------------------------------------------
// (3/4) View: patient_summary_view.php
// --------------------------------------------------------------------
// สร้าง View ใหม่ทั้งหมดที่: app/Views/reports/patient_summary_view.php
?>
<?= $this->extend('layout/default') ?>
<?= $this->section('content') ?>

<div class="container-fluid mt-4">
    <h3 class="mb-4">รายงานสรุปจำนวนผู้ป่วย แยกตามพื้นที่และระดับความเสี่ยง</h3>

    <!-- ส่วนของ Filter -->
    <div class="card shadow-sm mb-4">
        <div class="card-body">
            <div class="row g-3 align-items-end">
                <div class="col-md-4">
                    <label for="amphurFilter" class="form-label">เลือกอำเภอ</label>
                    <select id="amphurFilter" class="form-select">
                        <option value="">-- แสดงทุกอำเภอ --</option>
                        <?php foreach ($amphurs as $amphur): ?>
                            <option value="<?= $amphur['ampurcodefull'] ?>"><?= $amphur['ampurname'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="hospFilter" class="form-label">เลือก รพ.สต.</label>
                    <select id="hospFilter" class="form-select" disabled>
                        <option value="">-- แสดงทุก รพ.สต. ในอำเภอ --</option>
                    </select>
                </div>
                <div class="col-md-2">
                    <button id="searchBtn" class="btn btn-primary w-100">
                        <i class="fas fa-search"></i> ค้นหา
                    </button>
                </div>
                <div class="col-md-2">
                    <button id="resetBtn" class="btn btn-secondary w-100">
                        <i class="fas fa-sync-alt"></i> รีเซ็ต
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- ส่วนของตารางรายงาน -->
    <div class="card shadow-sm">
        <div class="card-body">
            <div class="table-responsive">
                <table id="reportTable" class="table table-bordered table-striped">
                    <thead id="reportHeader">
                        <!-- Header will be generated by JavaScript -->
                    </thead>
                    <tbody id="reportBody">
                        <!-- Body will be generated by JavaScript -->
                    </tbody>
                    <tfoot id="reportFooter">
                        <!-- Footer will be generated by JavaScript -->
                    </tfoot>
                </table>
            </div>
            <div id="loader" class="text-center my-5" style="display: none;">
                <div class="spinner-border text-primary" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script>
    $(document).ready(function() {

        // --- Event Handlers ---
        $('#amphurFilter').on('change', function() {
            const amphurCode = $(this).val();
            const hospFilter = $('#hospFilter');

            hospFilter.prop('disabled', true).html('<option value="">-- แสดงทุก รพ.สต. ในอำเภอ --</option>');

            if (amphurCode) {
                $.post("<?= site_url('reports/get-hospitals') ?>", {
                    amphur_code: amphurCode
                }, function(data) {
                    if (data.length > 0) {
                        data.forEach(hosp => {
                            hospFilter.append(`<option value="${hosp.hospcode}">${hosp.hospname}</option>`);
                        });
                        hospFilter.prop('disabled', false);
                    }
                }, 'json');
            }
        });

        $('#searchBtn').on('click', function() {
            fetchReportData();
        });

        $('#resetBtn').on('click', function() {
            $('#amphurFilter').val('').trigger('change');
            fetchReportData();
        });

        // --- Core Functions ---
        function fetchReportData() {
            const amphurCode = $('#amphurFilter').val();
            const hospCode = $('#hospFilter').val();

            $('#loader').show();
            $('#reportTable').hide();

            $.post("<?= site_url('reports/get-data') ?>", {
                    amphur_code: amphurCode,
                    hosp_code: hospCode
                })
                .done(function(response) {
                    renderReportTable(response);
                })
                .fail(function() {
                    Swal.fire('เกิดข้อผิดพลาด', 'ไม่สามารถดึงข้อมูลรายงานได้', 'error');
                })
                .always(function() {
                    $('#loader').hide();
                    $('#reportTable').show();
                });
        }

        function renderReportTable(response) {
            const header = $('#reportHeader');
            const body = $('#reportBody');
            const footer = $('#reportFooter');

            header.empty();
            body.empty();
            footer.empty();

            if (!response || !response.data) return;

            // 1. สร้าง Header
            let headerRow = '<tr><th rowspan="2">พื้นที่</th><th rowspan="2">รวม</th>';
            const riskLevels = response.riskLevels;
            headerRow += `<th colspan="${riskLevels.length}">ระดับความเสี่ยง</th></tr>`;
            let subHeaderRow = '<tr>';
            riskLevels.forEach(level => {
                subHeaderRow += `<th>${level.name}</th>`;
            });
            subHeaderRow += '</tr>';
            header.html(headerRow + subHeaderRow);

            // 2. สร้าง Body
            const totals = {
                total: 0
            };
            riskLevels.forEach(level => totals[`level_${level.id}`] = 0);

            response.data.forEach(row => {
                let tableRow = `<tr><td>${row.area_name || 'ไม่ระบุ'}</td><td>${row.total}</td>`;
                totals.total += parseInt(row.total || 0);

                riskLevels.forEach(level => {
                    const count = row[`level_${level.id}`] || 0;
                    tableRow += `<td>${count}</td>`;
                    totals[`level_${level.id}`] += parseInt(count);
                });
                tableRow += '</tr>';
                body.append(tableRow);
            });

            // 3. สร้าง Footer (Total)
            let footerRow = `<tr><th class="text-end">รวมทั้งหมด</th><th>${totals.total}</th>`;
            riskLevels.forEach(level => {
                footerRow += `<th>${totals[`level_${level.id}`]}</th>`;
            });
            footerRow += '</tr>';
            footer.html(footerRow);
        }

        // --- Initial Load ---
        fetchReportData();
    });
</script>
<?= $this->endSection() ?>